# Generated by Django 4.2 on 2024-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_phone_number_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_average",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
