# Generated by Django 4.2 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0004_registrations_max_units"),
        ("accounts", "0005_alter_profile_last_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="courses",
            field=models.ManyToManyField(to="pre_registration.course"),
        ),
    ]
