# Generated by Django 4.2 on 2024-12-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="courses",
        ),
    ]
