# Generated by Django 4.2 on 2024-12-30 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_profile_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_date",
            field=models.DateField(auto_now=True),
        ),
    ]
