# Generated by Django 4.2 on 2025-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_created_date_profile_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_average",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
