# Generated by Django 4.2 on 2025-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="max_units",
            field=models.IntegerField(default=20),
        ),
    ]
