# Generated by Django 4.2 on 2025-01-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_max_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_first_login",
        ),
    ]
