# Generated by Django 4.2 on 2024-11-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
        ("pre_registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrations",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
    ]
