# Generated by Django 4.2 on 2024-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0002_alter_registrations_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrations",
            name="course_id",
        ),
        migrations.AddField(
            model_name="registrations",
            name="course_id",
            field=models.ManyToManyField(to="pre_registration.course"),
        ),
    ]
