# Generated by Django 4.2 on 2024-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0003_remove_registrations_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrations",
            name="max_units",
            field=models.IntegerField(default=20),
        ),
    ]
