# Generated by Django 4.2 on 2024-12-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_courses"),
        ("pre_registration", "0004_registrations_max_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="mark",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequired_course",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequired_course_id",
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisite_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_courses",
                to="pre_registration.course",
            ),
        ),
        migrations.CreateModel(
            name="CourseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pre_registration.course",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_histories",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "course")},
            },
        ),
    ]
