# Generated by Django 4.2 on 2024-12-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "pre_registration",
            "0005_remove_course_mark_remove_course_prerequired_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursehistory",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_histories",
                to="pre_registration.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursehistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
