# Generated by Django 4.2 on 2024-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0007_course_have_prerequisite_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="prerequisite_course",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_courses",
                to="pre_registration.course",
            ),
        ),
    ]
