# Generated by Django 4.2 on 2024-12-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0010_course_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrations",
            old_name="course_id",
            new_name="courses_id",
        ),
    ]
