# Generated by Django 4.2 on 2025-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0012_remove_category_slug_remove_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursehistory",
            name="grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=4
            ),
        ),
    ]
