# Generated by Django 4.2 on 2025-01-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registration", "0013_alter_coursehistory_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrations",
            name="max_units",
        ),
    ]
